version: "3.9"

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./letsencrypt:/etc/letsencrypt
        depends_on:
          - keycloak
          - postgis
          - redis
        networks:
          - web

    certbot:
        image: certbot/dns-route53
        container_name: certbot
        environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          AWS_DEFAULT_REGION: us-east-1
        volumes:
          - ./letsencrypt:/etc/letsencrypt
        command: >
          certonly --dns-route53
          -d "*.altrinitytech.com"
          -d altrinitytech.com
          --non-interactive --agree-tos --email you@altrinitytech.com
        networks:
          - web

    # ✅ Combined PostGIS container (hosting both Keycloak and Geo databases)
    postgis:
        image: postgis/postgis:15-3.3
        container_name: postgis
        restart: always
        environment:
          POSTGRES_USER: altrinity
          POSTGRES_PASSWORD: altrinity
          POSTGRES_MULTIPLE_DATABASES: "keycloakdb,geodb"
        ports:
          - "5432:5432"
        volumes:
          - pg_data:/var/lib/postgresql/data
          - ./db/init:/docker-entrypoint-initdb.d
        networks:
          - web

    keycloak:
        image: quay.io/keycloak/keycloak:26.0.2
        command: ["start-dev", "--import-realm"]
        container_name: keycloak
        restart: always
        environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://postgis:5432/keycloakdb
          KC_DB_USERNAME: altrinity
          KC_DB_PASSWORD: altrinity
          KC_HOSTNAME: auth.altrinitytech.com
          KC_PROXY: edge
          KC_HTTP_ENABLED: true
          PROXY_ADDRESS_FORWARDING: true
          KC_PROXY_HEADERS: xforwarded
          KC_HTTP_RELATIVE_PATH: /
        ports:
          - "8080:8080"
        depends_on:
          - postgis
        volumes:
          - ./keycloak-realms:/opt/keycloak/data/import
        networks:
          - web

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
        networks:
          - web

    pgadmin:
        image: dpage/pgadmin4:8
        container_name: pgadmin
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@altrinitytech.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - "5050:80"
        volumes:
          - pgadmin_data:/var/lib/pgadmin
        depends_on:
          - postgis
        networks:
          - web

volumes:
  pg_data:
  pgadmin_data:

networks:
  web:
    driver: bridge