version: "3.9"

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./letsencrypt:/etc/letsencrypt
        depends_on:
          - keycloak
        networks:
          - web

    certbot:
        image: certbot/dns-route53
        container_name: certbot
        environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          AWS_DEFAULT_REGION: us-east-1
        volumes:
          - ./letsencrypt:/etc/letsencrypt
        command: >
          certonly --dns-route53
          -d "*.altrinitytech.com"
          -d altrinitytech.com
          --non-interactive --agree-tos --email you@altrinitytech.com
        networks:
          - web

    postgres:
        image: postgres:15
        restart: always
        environment:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
        volumes:
          - pg_data:/var/lib/postgresql/data
        networks:
          - web

    keycloak:
        image: quay.io/keycloak/keycloak:26.0.2
        command: ["start-dev", "--import-realm"]
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak
            KC_HOSTNAME: auth.altrinitytech.com
            KC_PROXY: edge
            KC_HTTP_ENABLED: true
            PROXY_ADDRESS_FORWARDING: true
            KC_PROXY_HEADERS: xforwarded
            KC_HTTP_RELATIVE_PATH: /
        ports:
          - "8080:8080"
        depends_on:
          - postgres
        volumes:
          - ./keycloak-realms:/opt/keycloak/data/import
        networks:
          - web

volumes:
  pg_data:

networks:
  web:
    driver: bridge