/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Admin': RouteRecordInfo<'/Admin', '/Admin', Record<never, never>, Record<never, never>>,
    '/CommandHub': RouteRecordInfo<'/CommandHub', '/CommandHub', Record<never, never>, Record<never, never>>,
    '/PendingApproval': RouteRecordInfo<'/PendingApproval', '/PendingApproval', Record<never, never>, Record<never, never>>,
    '/UserRoutes/[id]': RouteRecordInfo<'/UserRoutes/[id]', '/UserRoutes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/VolunteerMap': RouteRecordInfo<'/VolunteerMap', '/VolunteerMap', Record<never, never>, Record<never, never>>,
    '/VolunteerRoute/[routeId]': RouteRecordInfo<'/VolunteerRoute/[routeId]', '/VolunteerRoute/:routeId', { routeId: ParamValue<true> }, { routeId: ParamValue<false> }>,
    '/VolunteerRoute/[userId]': RouteRecordInfo<'/VolunteerRoute/[userId]', '/VolunteerRoute/:userId', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/Admin.vue': {
      routes: '/Admin'
      views: never
    }
    'src/pages/CommandHub.vue': {
      routes: '/CommandHub'
      views: never
    }
    'src/pages/PendingApproval.vue': {
      routes: '/PendingApproval'
      views: never
    }
    'src/pages/UserRoutes/[id].vue': {
      routes: '/UserRoutes/[id]'
      views: never
    }
    'src/pages/VolunteerMap.vue': {
      routes: '/VolunteerMap'
      views: never
    }
    'src/pages/VolunteerRoute/[routeId].vue': {
      routes: '/VolunteerRoute/[routeId]'
      views: never
    }
    'src/pages/VolunteerRoute/[userId].vue': {
      routes: '/VolunteerRoute/[userId]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
